const baseUrl="https://astrotalk-api.vercel.app/api/user";
// const baseUrl="http://localhost:4000/api/user";

export const Apis ={
    ratingUrl: baseUrl+"/rating",
    googleLoginUrl: baseUrl+"/login_by_google",
    followerUrl: baseUrl+"/follower",
    alertUrl: baseUrl + "/alerts",
    profileUrl:baseUrl + "/user_profile",
    logoutUrl:baseUrl + "/logout",
    albumsUrl:baseUrl+"/album_list", 
    hostsList:baseUrl+"/hosts_list", 
    hostProfile:baseUrl+"/host_profile",
    editalbumUrl:baseUrl+"/album_content",
    addalbumUrl:baseUrl+"/album",
    deletealbum:baseUrl+"/album",
    searchalbumUrl: baseUrl+"/find_album",
    notificationsUrl: baseUrl+"/notifications",
    faqUrl:baseUrl+"/faq",
    servicesUrl:baseUrl+"/host_services_rate",
    servicessaveUrl:baseUrl+"/host_services_rate",
    socialprofileUrl:baseUrl+"/host_social_profile",
    updateprofile:baseUrl+"/host_social_profile",
    userlistUrl:baseUrl+"/report_user",
    blockuserUrl:baseUrl+"/block_user",
    geoLocationApi: baseUrl+"/user_geolocation",
    addPayment: baseUrl+"/host_payment_account",
    getPayments: baseUrl+"/host_payment_account?page=0&size=100",
    deletePayment: baseUrl+"/host_payment_account",
    getPaymentsById: baseUrl+"/find_host_payment_account",
    createTimeSlot: baseUrl+"/host_timeslot",
    getTimeSlot: baseUrl+"/host_timeslot",
    deleteTImeSlot: baseUrl+"/host_timeslot",
    referralList: baseUrl+"/host_referred_host",
    addRefefer: baseUrl+"/host_referred_host",
    verifyReferalcode: baseUrl+"/host_referral_code",
    refferalCodelinks: baseUrl+"/host_referral_info",
    checkReferal: baseUrl+"/host_check_referred",
    uplaodprofileapi:baseUrl+"/upload_profile_pic",
    editalbumphotovideo:baseUrl+"/upload_album_content",
    editalbumdeletd:baseUrl+"/album_content",
    pancard:baseUrl+"/hostKYC_upload_pan_card",
    addressproof:baseUrl+"/hostKYC_upload_address_proof",
    uploadphoto:baseUrl+"/hostKYC_upload_photo_id",
    kYcsave:baseUrl+"/hostKYC",
    kycinfo:baseUrl+"/hostKYC",
    hostRegister:baseUrl+"/register_by_email",
    hostLogin:baseUrl+"/login_by_email",
    hostforgetpassword :baseUrl+"/forgot_password",
    hostchangePassword:baseUrl+"/change_password_by_otp",
    hostemailotp:baseUrl+"/verify_email_by_otp",
    resendcode:baseUrl+"/resend_email_otp",
    phoneverifyotp:baseUrl+"/verify_phone_by_otp",
    phoneresend:baseUrl+"/resend_phone_otp",
    sendverificationcode:baseUrl+"/send_phone_verification_code",
    pg_create_order:baseUrl+"/pg_create_order",
    pg_verify_payment:baseUrl+"/pg_verify_payment",

}